name: lock_connect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/  # <-- Registering the IMAGES folder
    - assets/videos/
    - assets/logo.png
    - assets/capsule.png
    - assets/lock_animation.mp4
    - assets/animation.gif
    - assets/anima.gif
    - assets/images/capsule.png


  fonts:
   - family: PlayfairDisplay
     fonts:
      - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
      - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
   - family: Roboto
     fonts:
      - asset: assets/fonts/Roboto-Bold.ttf
      - asset: assets/fonts/Roboto-Italic.ttf
      - asset: assets/fonts/Roboto-Regular.ttf


