name: lock_connect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.7.2
  image_picker: ^1.0.7
  gal: ^1.1.1
  firebase_storage: ^11.6.0
  url_launcher: ^6.2.5
  # -------------------------------------
  firebase_core: ^2.27.1      # Core services
  firebase_auth: ^4.17.9      # Authentication (Login/Signup)
  cloud_firestore: ^4.15.9    # Database (User Profiles, Capsules)
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/  # <-- Registering the IMAGES folder
    - assets/videos/
    - assets/logo.png
    - assets/capsule.png
    - assets/lock_animation.mp4
    - assets/animation.gif
    - assets/anima.gif
    - assets/images/capsule.png


  fonts:
   - family: PlayfairDisplay
     fonts:
      - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
      - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
   - family: Roboto
     fonts:
      - asset: assets/fonts/Roboto-Bold.ttf
      - asset: assets/fonts/Roboto-Italic.ttf
      - asset: assets/fonts/Roboto-Regular.ttf


